# Generated by Django 5.2.1 on 2025-05-20 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_documento', models.IntegerField()),
                ('fecha_alta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_legajo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_reserva', models.DateTimeField()),
                ('fecha_solicitada_reserva', models.DateTimeField()),
                ('coordinador_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to='servicios.coordinador')),
                ('empleado_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='servicios.empleado')),
                ('servicio_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='servicios.servicio')),
            ],
        ),
    ]
