# Generated by Django 5.2.1 on 2025-05-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_coordinador_empleado_reservaservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinador',
            options={'verbose_name_plural': 'Coordinadores'},
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='servicios.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_registro_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
