# Generated by Django 5.2.1 on 2025-05-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero_documento', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Coordinadores',
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_indicada_reserva', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.coordinador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'ordering': ['fecha_indicada_reserva'],
            },
        ),
    ]
